<?xml version="1.0"?>
<!DOCTYPE demolist [
  <!ELEMENT demolist (demo+)>
  <!ELEMENT demo (name,called_from,model_file)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT called_from (#PCDATA)>
  <!ELEMENT model_file (#PCDATA)>
]>
<demolist>
  <demo>
    <name>DSP Builder Tutorial</name>
    <called_from>DSPBuilderTutorial.html</called_from>
    <model_file>\Tutorials\GettingStartedSinMdl\singen.mdl</model_file>
  </demo>
  <demo>
    <name>Hardware in the loop - FreqSweep</name>
    <called_from>FrequencySweep.html</called_from>
    <model_file>\Tutorials\HIL\FreqSweep\FreqSweep_HIL.mdl</model_file>
  </demo>
  <demo>
    <name>CIC Interpolation (3 stages x75)</name>
    <called_from>CICInterpolate.html</called_from>
    <model_file>\Demos\Filters\CicFilter\CiCInterpolator75.mdl</model_file>
  </demo>
  <demo>
    <name>CIC Decimation (3 stages x75)</name>
    <called_from>CICDecimate.html</called_from>
    <model_file>\Demos\Filters\CicFilter\CicDecimator75.mdl</model_file>
  </demo>
  <demo>
    <name>Convolution Interleaver DeInterleaver</name>
    <called_from>ConvolutionInterleaverDeinterleaver.html</called_from>
    <model_file>\Demos\Transforms\CrossInterleaver12x17\top12x17.mdl</model_file>
  </demo>
  <demo>
    <name>SOPC Builder Peripheral</name>
    <called_from>SOPCBuilderPeripheral.html</called_from>
    <model_file>\Tutorials\SOPCBuilder\SOPCBlock\topavalon.mdl</model_file>
  </demo>
  <demo>
    <name>IIR Filter</name>
    <called_from>IIRFilter.html</called_from>
    <model_file>\Demos\Filters\IIROrder2\topiir.mdl</model_file>
  </demo>
  <demo>
    <name>FIR Filter using 4-8 Inputs LUT</name>
    <called_from>FIRFilter.html</called_from>
    <model_file>\Demos\Filters\DA32\AltrFir32.mdl</model_file>
  </demo>
  <demo>
    <name>MAC Based 32 TAP FIR Filter</name>
    <called_from>MAC32FIRFilter.html</called_from>
    <model_file>\Demos\Filters\Mac32\FIR_MAC32.mdl</model_file>
  </demo>
  <demo>
    <name>Color Space Converter</name>
    <called_from>ColorSpaceConverter.html</called_from>
    <model_file>\Demos\Transforms\Csc\TopCsc.mdl</model_file>
  </demo>
  <demo>
    <name>Farrow Based Resampler</name>
    <called_from>FarrowResample.html</called_from>
    <model_file>\Demos\Filters\FarrowResamp\FarrowResamp.mdl</model_file>
  </demo>
  <demo>
    <name>Cordic, 20 bits, Rotation mode</name>
    <called_from>Cordic.html</called_from>
    <model_file>\Demos\Transforms\Cordic\DemoCordic.mdl</model_file>
  </demo>
  <demo>
    <name>Imaging Edge Detection</name>
    <called_from>EdgeDetection.html</called_from>
    <model_file>\Demos\Video\EdgeDetection\Edge_detector.mdl</model_file>
  </demo>
  <demo>
    <name>Quartus II Assignment Setting Example</name>
    <called_from>QuartusAssignmentSetting.html</called_from>
    <model_file>\Demos\QuartusIIConstraints\Top2S60Board.mdl</model_file>
  </demo>
  <demo>
    <name>SignalTap II - Filtering Lab</name>
    <called_from>SignalTapFilteringLab.html</called_from>
    <model_file>\Demos\Filters\FilteringLab\Sim\FilteringLab.mdl</model_file>
  </demo>
  <demo>
    <name>SignalTap II - Filtering Lab with DAC to ADC loopback</name>
    <called_from>SignalTapFilteringLabWithLoopback.html</called_from>
    <model_file>\Demos\Filters\FilteringLab\Stap\StFilteringLab.mdl</model_file>
  </demo>
   <demo>
    <name>Cyclone II DE2 Board</name>
    <called_from>CycloneDE2.html</called_from>
    <model_file>\Demos\Board\CycloneII_DSPBoard_DE2\TestDE2Board.mdl</model_file>
  </demo>
  <demo>
    <name>Cyclone II EP2C35 DSP Board</name>
    <called_from>CycloneEP2C35.html</called_from>
    <model_file>\Demos\Board\CycloneII_DSPBoard_2C35\Test2C35Board.mdl</model_file>
  </demo>
  <demo>
    <name>Cyclone II EP2C70 DSP Board</name>
    <called_from>CycloneEP2C70.html</called_from>
    <model_file>\Demos\Board\CycloneII_DSPBoard_2C70\Test2C70Board.mdl</model_file>
  </demo>
   <demo>
    <name>Cyclone III EP3C25 DSP Board</name>
    <called_from>CycloneEP3C25.html</called_from>
    <model_file>\Demos\Board\CycloneIII_DSPBoard_3C25\Test3C25Board.mdl</model_file>
  </demo>
  <demo>
    <name>Stratix EP1S25 DSP Board</name>
    <called_from>StratixEP1S25Demo.html</called_from>
    <model_file>\Demos\Board\Stratix_DSPBoard_1S25\Test1S25Board.mdl</model_file>
  </demo>
  <demo>
    <name>Stratix EP1S80 DSP Board</name>
    <called_from>StratixEP1S80Demo.html</called_from>
    <model_file>\Demos\Board\Stratix_DSPBoard_1S80\Test1S80Board.mdl</model_file>
  </demo>
  <demo>
    <name>Stratix II EP2S60 DSP Board</name>
    <called_from>StratixEP2S60.html</called_from>
    <model_file>\Demos\Board\StratixII_DSPBoard_2S60\Test2S60Board.mdl</model_file>
  </demo>
  <demo>
    <name>Stratix II EP2S180 DSP Board</name>
    <called_from>StratixEP2S180Demo.html</called_from>
    <model_file>\Demos\Board\StratixII_DSPBoard_2S180\Test2S180Board.mdl</model_file>
  </demo>
    <demo>
    <name>Stratix II EP2S90GX PCI Express Board</name>
    <called_from>StratixEP2S90GXPCIDemo.html</called_from>
    <model_file>\Demos\Board\StratixII_DSPBoard_2S90GX\Test2S90GXBoard.mdl</model_file>
  </demo>
</demolist>
